Create test.yml
under-the-oaks/ColdCase-Client pull request #43
Opened 2024-11-06 19:02 UTC by jonachri

Trying to automate the testing when pull-requesting on development-Branch.

Closes #42 
Closes #28

2024-11-09 23:28 UTC, Danmyrer approved these changes

2024-11-09 23:28 UTC, Danmyrer commented on .github/workflows/test.yml
Vielleicht zu actions.yml umbenennen

2024-11-09 23:29 UTC, MaxRBecker requested changes

2024-11-09 23:29 UTC, MaxRBecker commented on .github/workflows/test.yml
> +        if: failure()
```suggestion
        
```

It would be good to also see the test report if no test failed, to validate if all tests ran.

2024-11-10 10:48 UTC, MaxRBecker approved these changes
LGTM

2024-11-10 18:49 UTC, merged