15 create player objekt
under-the-oaks/ColdCase-Client pull request #44
Opened 2024-11-07 13:32 UTC by MaxRBecker

![image](https://github.com/user-attachments/assets/17063ffb-23ec-4995-94cc-96e53bfb22a5)

2024-11-09 13:17 UTC, Danmyrer requested changes
Player itself looks fine but the way it is instanciated (see comments) breaks the way we handle different TileContents (that get instanciated using the TileContents-Enum)

2024-11-09 13:17 UTC, Danmyrer commented on core/src/main/java/tech/underoaks/coldcase/data/Map.java
> +    static float tileSize = 32;
JavaDoc since usage of TileSize is not immediately clear

2024-11-09 13:17 UTC, Danmyrer commented on core/src/main/java/tech/underoaks/coldcase/data/Map.java
>                      int temp = rawTiles.get(i).get(j);
Was passiert hier? Sollte der Player nicht als TileContent genau so wie alle anderen TileContents in `tiles.get(i).get(j).setTileContent(......)` initialisiert werden? Wenn wir den player in der Map Klasse vorher mit der `temp`-variable abfangen dann ist das inkonsistent gegenüber den enum `TileContents` wo alle anderen Contents herkommen.

2024-11-09 13:17 UTC, Danmyrer commented on core/src/main/java/tech/underoaks/coldcase/data/Map.java
> +                float tempX = x * tileSize / 2 * -1;
Hier X und Y tauschen um noch die Tileorientierung zu Fixen

2024-11-09 13:17 UTC, Danmyrer commented on assets/maps/test_plain/map.content
> +1 0 0 0 0 2 0
Wenn wir hier den Player mit der Zahl '2' initialisieren dann sollte der Player auch in dem TileContents-Enum erstellt werden.

2024-11-09 13:21 UTC, MaxRBecker commented on core/src/main/java/tech/underoaks/coldcase/data/Map.java
>                      int temp = rawTiles.get(i).get(j);
Ja, um den Spieler Input zu machen, muss auf dem Player Objekt jeden Frame update gecalled werden. Natürlich ist es auch möglich, das ganze über den Gamecontroller zu machen. Dazu muss der nur erstmal existieren. Im zuge dessen würde ich diesen PR auf draft setzten und auf den GC warten

2024-11-10 22:05 UTC, Danmyrer approved these changes
LGTM

2024-11-10 22:05 UTC, merged