29 test map class
under-the-oaks/ColdCase-Client pull request #72
Opened 2024-11-14 17:32 UTC by jonachri

2024-11-14 18:42 UTC, MaxRBecker requested changes

2024-11-14 18:42 UTC, MaxRBecker commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    }
Das kann meines Achtens alles mit mockito gemockt werden. https://stackoverflow.com/questions/1087339/using-mockito-to-test-abstract-classes

2024-11-16 08:13 UTC, Danmyrer requested changes

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/HeadlessApplicationListener.java
> +public class HeadlessApplicationListener extends Main {
JavaDoc

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +class MapTest{
JavaDoc

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    static class EmptyUpdate extends GameStateUpdate{
JavaDoc

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    static class TestTileContent extends TileContent {
JavaDoc

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    static class BrokenTileContent extends TileContent {
JavaDoc

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +        // TODO - Soll das so sein?
Bug Issue Aufnehmen

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +        // Nicht ausreichend
Ist ausreichend, sollte alles testen

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    public void GetMatrixWidthAndHeightTest(){
Ich bin mir nicht sicher ob getmatrixwidth überhaupt getestet werden muss. Es handelt sich hierbei um eine Hilfsmethode die mit der Ablösung von getMap ohnehin deprecated ist.

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    public void UpdateMapTest() {
Tests notwendig

2024-11-16 08:13 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    public void UpdateMapUntilStableTest() {
Tests notwendig

2024-11-16 12:29 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    public void GetMatrixWidthAndHeightTest(){
See #73

2024-11-16 12:29 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    public void UpdateMapTest() {
See #73

2024-11-16 12:29 UTC, Danmyrer commented on core/src/test/java/tech/underoaks/coldcase/MapTest.java
> +    public void UpdateMapUntilStableTest() {
See #73

2024-11-16 13:24 UTC, Danmyrer approved these changes
LGTM

2024-11-16 15:00 UTC, MaxRBecker approved these changes

2024-11-16 15:08 UTC, merged