[#53] -Added basic InventoryUI
under-the-oaks/ColdCase-Client pull request #92
Opened 2024-11-24 12:34 UTC by jonachri

-Added UItextures Enum
-Added inventory sprite

2024-11-24 12:38 UTC, jonachri commented
Frage, die noch offen ist, bleibt wohin wir die renderInventory() hin auslagern.

2024-11-26 10:32 UTC, MaxRBecker requested changes

2024-11-26 10:32 UTC, MaxRBecker commented on core/src/main/java/tech/underoaks/coldcase/state/tileContent/UITextures.java
> +    }
Wäre besser als Feld im Item TileContent

2024-12-03 09:40 UTC, jonachri commented on core/src/main/java/tech/underoaks/coldcase/state/tileContent/UITextures.java
> +    }
*Feld im ItemObject

2024-12-05 14:06 UTC, MaxRBecker approved these changes
LGTM

2024-12-05 14:06 UTC, merged